### ISSUE TITLE
scan_interval doesn't working

### ISSUE THREAD

**Issue by ruvasik** [iprak/yahoofinance#105]
v 1.2.2
```
yahoofinance:
  symbols:
...
  scan_interval: 900
```
All symbols update every 6 hours.

**Comment by iprak** [comment]
I am seeing the scan_interval being respected. Is this for all symbols or for just one?

If enable info level logging like this and restart, then you should see messages about updates.

```
logger:
  default: warn
  logs:    
    custom_components.yahoofinance: info
```
