### ISSUE TITLE
Global scan_interval always 5 minutes, symbol scan_interval works

### ISSUE THREAD

**Issue by Soukyuu** [iprak/yahoofinance#114]
Using version 1.2.4

![image](https://github.com/iprak/yahoofinance/assets/2095054/52482dc6-e4dd-4b22-beaa-27a8fa0976e4)

This is me experimenting with a symbol, you can see it has different refresh intervals. The symbol has a lot of trade volume today, so it's not that there wasn't a value change in between. Please ignore the spike at around 14:16, restarted HA there trying to make it refresh more often.

The first part with 5 minute interval refreshes is this:
```
yahoofinance:
  show_trending_icon: true
  decimal_places: 2
  scan_interval: 60
  symbols:
    - symbol: ADYEN.AS
    - symbol: O
      target_currency: EUR
```
While the second one is:
```
yahoofinance:
  show_trending_icon: true
  decimal_places: 2
  symbols:
    - symbol: ADYEN.AS
      scan_interval: 60
    - symbol: O
      scan_interval: 60
      target_currency: EUR
```
I have started with the official example in the docs, so using `- minutes: 5` then changing it to `1` before restarting Home Assistant for the first time...
