### ISSUE TITLE
sensors don't get removed

### ISSUE THREAD

**Issue by mguilherme** [iprak/yahoofinance#122]
after removing a few symbols the sensors still exist but shown as unavailable:

<img width="949" alt="image" src="https://github.com/iprak/yahoofinance/assets/699510/37b74d5e-168f-49df-908e-a0778a2029ed">

is it possible to remove it?

currently my yaml has 2 symbols which work just fine, but the ones I removed are there but unavailable

```yaml
yahoofinance:
  symbols:
    - BTC-USD
    - ETH-USD
```
