### ISSUE TITLE
Trending argument not honored?

### ISSUE THREAD

**Issue by oliv3r** [iprak/yahoofinance#134]
Having just installed yahoo finance, and using the sensor also in my gnome-desktop, I was a bit 'annoyed' by the fact it was print 'EUR' instead of €, which saves some space. Going over the documentation, I found that I could even replace it with the trending status, which was even more useful. I can 'imagine' € :p

So I copy pasted some config values:

```yaml
show_trending_icon: true
scan_interval:
  hours: 6
include_fifty_day_values: false
include_post_values: false
include_pre_values: false
symbols:
  - xxx
  - yyy
  - zzz
```

Did I typo paste something?

**Comment by iprak** [comment]
`show_trending_icon` is working as described. `Trending icons (trending-up, trending-down or trending-neutral) can be displayed instead of currency based icon by specifying show_trending_icon. The `unit_of_measurement` is still USD and that is what HomeAssistant display.

**Comment by oliv3r** [comment]
> show_trending_icon is working as described.

But what am I supposed to see :), I see '12.45 EUR' where I would have expected '12.45 ↗'

Actually, I was thinking, would it be difficult to define your own format in the yaml?

Something like:
```yaml
symbols:
   - xxx
     format: '%currency_symbol %value_comma %trending_arrow'
```

Where `%value_period` would be the alternative to deal with locale issues. I don't know if locale is even handled properly anyways, but I'd be happy with `%value` :p

Would even be cool to have `%trending_arrow_colored` to get a green/red/neutral arrow in this case.

anyway, would be nice to have more control over the formatting of the symbol, instead of trying to solve it with flags?
