### ISSUE TITLE
Feature request - Icon state related colors (Also doc addition suggestion for indexes)

### ISSUE THREAD

**Issue by rpitera** [iprak/yahoofinance#14]
First, thanks for this integration!  Gave up on having stocks in HA a long time ago; integrations were unreliable, doing it via REST sensors involved a lot of work and hard to find APIs.  Then I found this in HACS and was super happy someone was finally developing something that works!

Request:  Would it be possible to include coloring for the icons based on the state of the entity?  Either user input config or even simple Red/Yellow/Green for Trending Down/Neutral/Trending Up states.  I'd just like that immediate visual recognition and I think it would add to the function/features.

Also:  Discovered that I could add indexes by using the symbol and caret; e.g.

```
- platform: yahoofinance
  show_trending_icon: true
  scan_interval:
    minutes: 15
  symbols:
    - ^DJI
    - ^IXIC
    - ^VIX
    - AAPL
    - AMZN
    - GOOGL
    - UPS
    - UNM
```

Works great in case you want to add this to the docs; you can get the index abbreviation from the URL in the Yahoo Finance page.  Thanks!
