### ISSUE TITLE
unit_of_measurement is an invalid option for yahoo finance

### ISSUE THREAD

**Issue by Ham60elu** [iprak/yahoofinance#149]
I am trying to suppress the currency unit for the index symbols as described in the readme:

"The **unit_of_measurement** can be suppressed by setting **no_unit: true**. This could be used for index symbols if no currency unit is desired to be displayed."

Here is that part of my configuration.yaml:

```
yahoofinance:
  symbols:
    - symbol: ^GDAXI  # Dax Index
       unit_of_measurement:
         no_unit: true
    - symbol: ^DJI    # Dow Jones Index
       unit_of_measurement:
         no_unit: true
```
....
When checking the configuration, it says **"unit_of_measurement is an invalid option for yahoo finance"** and after rebooting HA the currency unit is still there. Unfortunately there is no example for that in the readme file.
