### ISSUE TITLE
FEATURE REQUEST: buy details

### ISSUE THREAD

**Issue by ReenigneArcher** [iprak/yahoofinance#15]
I have a feature request.

It would be nice to be able to enter details about the initial purchase of the stock, without creating an additional template entity for each symbol. For example:

```
sensor:
  - platform: yahoofinance
    symbols:
      - SYMBOL
        quantity: 43
        cost_per_share: 3.52
        date: 2020-04-29
```

Then add some additional attributes:

- Cost basis (cost_per_share * quantity)
- Gain/loss % (total since purchase)
- Gain/loss $ (total since purchase)
- Day change $ (current daily change * quantity)
- Market value (quantity * current price)
- Short/Long Term (boolean, 0=short term (held less than 1 year), 1=long term (held greater than 1 year))

Finally having some new entities could provide useful as well.

- Total market value (all stocks combined current value)
- Total cost basis (all stocks combined, value at purchase)
- Total day change % (All stocks in yaml list)
- Total day change $ (All stocks in yaml list)
- Total gain loss % (All stocks in yaml difference of current value from purchased value)
- Total gain loss $ (All stocks in yaml difference of current value from purchased value)
