### ISSUE TITLE
ticker list doesn't update when I reload YAML

### ISSUE THREAD

**Issue by knwpsk** [iprak/yahoofinance#158]
Just installed this extension via HACS. (Thank you!!)

When I add new ticker symbols in config.yaml, then in Dev Tools > Reload All YAML, the new tickers don't get picked up. In order to see the new entities I have to do a full HA restart. 

(This was true even when I only had one stock (TSLA) to try it out. I don't think the index or futures tickers are the problem.)

Is this expected?

My config:

```
yahoofinance:
  include_post_values: true
  include_pre_values: true
  show_trending_icon: true
  decimal_places: 2
  scan_interval:
    minutes: 5
  symbols:
    - ^VIX
    - SPY
    - DIA
    - MES=F
```
