### ISSUE TITLE
Currency Exchange

### ISSUE THREAD

**Issue by olines** [iprak/yahoofinance#19]
v1.0.0 appears to have broken the ability to include currency exchange rates? - working ok for me in v0.4:

```
- platform: yahoofinance
    symbols:
      - USDEUR=X
```
Thank you!

**Comment by iprak** [comment]
It should be working, however the platform declaration is different now. e.g.
```yaml
yahoofinance:
  symbols:
    - ISTNX
```

Let me know if that doesn't work.
