### ISSUE TITLE
target_currency goes back to DOLLARS

### ISSUE THREAD

**Issue by unosakk** [iprak/yahoofinance#45]
```
yahoofinance:
    symbols:
      - symbol: RBOT.L
        target_currency: EUR
      - symbol: ECAR.L
        target_currency: EUR
```
        
After the first update, that shows up as EUR. It will set the currency as dollars again.
![image](https://user-images.githubusercontent.com/67309358/119137065-11dce400-ba49-11eb-8752-cbda5bd4baa3.png)
