### ISSUE TITLE
Option to add owned shares in config and possibly calculate market value of holdings?

### ISSUE THREAD

**Issue by imist** [iprak/yahoofinance#53]
It would be nice to have the option to add number of shares owned in the config like this:

```
symbols:
  - symbol: AAPL
    shares: 100
  - symbol: MSFT
    shares: 10
```

This would in turn make it possible to add the attributes `shares` and `market_value` (shares * state/regularMarketPrice) to each stock entity :-)
