### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by kitkat270** [iprak/yahoofinance#68]
Log error after installing via HACS;

`2022-01-08 16:04:13 ERROR (MainThread) [homeassistant.components.hassio] The system cannot restart because the configuration is not valid: Integration error: yahoofinance - Integration 'yahoofinance' not found.`

Fully accept i might be doing something wrong, but can't see what?

![Screenshot 2022-01-08 at 16 14 28](https://user-images.githubusercontent.com/28577458/148651495-61e4674a-34e6-4018-a178-3265fd8a6005.png)

Configuration.yaml

```
yahoofinance:
  symbols:
    - HSBA.L
    - TEF.MC
  scan_interval:
    hours: 2
  show_trending_icon: true
```

Thanks.
