### ISSUE TITLE
Support for cryptocurrencies

### ISSUE THREAD

**Issue by leogaggl** [iprak/yahoofinance#72]
It would be extremely useful to also get cryptocurrencies to report via Yahoo Finance

https://finance.yahoo.com/quote/BTC-EUR

Have tried several symbols, but not working.

**Comment by iprak** [comment]
BTC-EUR should work. I saw your comment in the other thread, is that the same issue?

**Comment by iprak** [comment]
Here is a sample declaration for BTC symbol which seems to work.

```
yahoofinance:
    symbols:
        - BTC-USD
        - BTC-EUR 
```

**Comment by leogaggl** [comment]
None of the cryptocurrency pairs returns any data.

I can definitely not get any of these work.

**Comment by iprak** [comment]
I have just have this (in configuration.yaml) and get data back. Can you enable debug logging as shown before, it might show what is happening.

```
yahoofinance:
    symbols:
        - BTC-USD
        - BTC-EUR            
    
logger:
  default: info
  logs:
    custom_components.yahoofinance: debug
```
